In [1]:
# 1부터 100까지의 수 중에서 3과 5의 공배수만 출력하세요..
for i in range(1, 101):
  if i % 3 == 0 and i % 5 == 0:
    print(i)

15
30
45
60
75
90

In [2]:
# 1부터 50까지의 수 중 짝수의 합과 홀수의 합을 각각 구해 출력하는 프로그램을 작성하세요.
even_sum = 0
odd_sum = 0
for i in range(1, 51):
  if i % 2 == 0:
    even_sum += i
  else:
    odd_sum += i
even_sum, odd_sum

(650, 625)

In [5]:
# 튜플 (10, 20, 30)을 변수 a, b, c에 언패킹하여 각각 출력하세요.
t  = (10, 20, 30)
a, b, c = t
print(a)
print(b)
print(c)

10
20
30

In [6]:
# 다음 데이터를 이용해 Pandas DataFrame을 생성하고 출력하세요.
# 딕셔너리 형태 데이터 생성
data = {
    '이름' : ['kim', 'lee'],
    "나이" : [25,23],
    "도시" : ['서울','부산']
}

import pandas as pd

df = pd.DataFrame(data)
df

    이름  나이  도시
0  kim  25  서울
1  lee  23  부산

In [8]:
# 위에서 만든 DataFrame에서 이름 열만 선택해 출력하세요.
df['나이']

0    25
1    23
Name: 나이, dtype: int64

In [9]:
# 점수라는 새로운 열을 추가하고 [90, 85] 값을 넣은 뒤 DataFrame을 출력하세요.
df['점수'] = [90, 95]
df

    이름  나이  도시  점수
0  kim  25  서울  90
1  lee  23  부산  95

In [10]:
# 문자열에서 모든 알파벳만 찾아 출력하세요. 정규표현식
text = 'python is fun 32489042308934289034890234089!!!!!!!!!!!!!!!!!!!!!!'

import re
result = re.findall(r'[A-Za-z]+', text)
result

['python', 'is', 'fun']

In [ ]:
'''
stack
Last In, First out
책더미, 접시 쌓기, 프링글스
'''

In [12]:
stack = []

stack.append(1)
stack.append(2)
stack.append(3)

stack.pop()

3

In [13]:
stack

[1, 2]

In [ ]:
'''
Queue
First In, First out
줄 서기, 프린터 대기열, 편의점 선입선출
'''

In [15]:
queue = []

queue.append(1)
queue.append(2)
queue.append(3)

queue.pop(0)

1

In [16]:
queue

[2, 3]

In [ ]:
'''
dfs
depth first search
깊이 우선 탐색
한방향으로 깊이 들어간 다음 막히면 다른길을 탐색

bfs
breadth first search
너비 우선 탐색
시작 노드 가까운 노드를 넓게 탐색
'''

In [19]:
'''
판다스
'''
import pandas as pd

scores = pd.Series([85,90,78,95])
scores, type(scores)

(0    85
 1    90
 2    78
 3    95
 dtype: int64,
 pandas.core.series.Series)

In [20]:
scores.shape

(4,)

In [36]:
# DataFrame
# 행, 열 2차원
datas = [
    [85, 90, 78, 92, 88],
    [95, 85, 88, 90, 82],
    [88, 92, 85, 87, 90],
    [90, 89, 85, 91, 87]
]
cols = ['수학','영어','과학','역사', '도덕']

df = pd.DataFrame(datas, columns=cols)
df

   수학  영어  과학  역사  도덕
0  85  90  78  92  88
1  95  85  88  90  82
2  88  92  85  87  90
3  90  89  85  91  87

In [37]:
df.head(1)

   수학  영어  과학  역사  도덕
0  85  90  78  92  88

In [38]:
df.tail(3)

   수학  영어  과학  역사  도덕
1  95  85  88  90  82
2  88  92  85  87  90
3  90  89  85  91  87

In [39]:
df['과학'][:3]

0    78
1    88
2    85
Name: 과학, dtype: int64

In [40]:
df['수학'] > 80

0    True
1    True
2    True
3    True
Name: 수학, dtype: bool

In [41]:
df[df['수학']>=90]

   수학  영어  과학  역사  도덕
1  95  85  88  90  82
3  90  89  85  91  87

In [42]:
df['수학'].mean()

np.float64(89.5)

In [46]:
i = int(input())
if i == 4:
  print('두산')
elif i == '4':
  print('로키')
elif i < 5:
  print('부트캠프')

2
부트캠프

In [47]:
i = '4'
i = int(i)
i

4

In [ ]:
'''
csv
Comma-Separated Values

txt

yaml
xml

jpg
png

avi

pdf
'''